run:
  timeout: 5m

linters:
  enable-all: true
  disable:
    - depguard
    - wsl
    - exhaustruct
    - gochecknoglobals
    - gofumpt
    - varnamelen
    - nlreturn
    - gomoddirectives

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
