name: Pipeline
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
      - name: Sync configs
        run: ./scripts/sync-configs.sh
      - name: Run linter
        run: make lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
      - name: Sync configs
        run: ./scripts/sync-configs.sh
      - name: Run tests
        run: make tests

  deploy:
    name: Deploy to CD Server
    needs: [test, lint]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: RestartFU/cd/.github/workflows/deploy.yml@master
    with:
      environment: production
      env_vars: "BUILD_NUMBER=${{ github.run_number }}"
      include_github_secrets: true
    secrets:
      CD_SERVER_HOST: ${{ secrets.CD_SERVER_HOST }}
      CD_API_KEY: ${{ secrets.CD_API_KEY }}
